name: Build

on:
  pull_request:
    branches:
      - master
      - sr-64-github-action-coverage-reporter-crashing-on-windows
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      # If this step breaks, try inspecting MSVC directory and consider changing appropriate paths.
      #
      #   ls 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\'
      #
      # Since windows runner can be updated the version can change in future releases.
      - name: Install SQLite3 + generate sqlite3.lib
        run: |
          choco install sqlite -y
          cd C:\ProgramData\chocolatey\lib\SQLite\tools
          ls 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\'
          & 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\lib.exe' /DEF:sqlite3.def /OUT:sqlite3.lib /MACHINE:x64
          cp sqlite3.lib 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\lib\x64'

      - name: Set static paths test
        run: |
          echo $env:CRYSTAL_LIBRARY_RPATH
          echo $env:CRYSTAL_LIBRARY_PATH

          echo ("CRYSTAL_LIBRARY_RPATH='C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\lib\x64/'" + $env:CRYSTAL_LIBRARY_RPATH) >> $env:GITHUB_ENV
          echo ("CRYSTAL_LIBRARY_PATH='C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.37.32822\lib\x64/'" + $env:CRYSTAL_LIBRARY_PATH) >> $env:GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.9

      - run: shards install --production

      - run: crystal build src\cli.cr -o dist\coveralls --release --static --no-debug --progress
      - run: |
          cd dist
          tar -acf coveralls-windows.zip coveralls.exe

      - name: Upload exe
        uses: actions/upload-artifact@v3
        with:
          name: coveralls-windows.exe
          path: dist/coveralls.exe
          if-no-files-found: error

      - name: Upload zip
        uses: actions/upload-artifact@v3
        with:
          name: coveralls-windows.zip
          path: dist/coveralls-windows.zip
          if-no-files-found: error

